name: 'Action FTP Sync'
description: 'This action syncs a local dir with a remote dir via FTP using hashes for finding differences in files.'
inputs:
  host:
    description: 'host description'
    required: true
  port:
    description: 'port description'
    required: true
    default: 21
  username:
    description: 'username description'
    required: true
  password:
    description: 'password description'
    required: true
  localDir:
    description: 'localDir description'
    required: true
  remoteDir:
    description: 'remoteDir description'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'